// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: proto/attribute.proto

package calculation

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// ChiYu Buff
// Next field: 4
type ChiYu int32

const (
	ChiYu_CY_QIANG_DU  ChiYu = 0
	ChiYu_CY_HUI_XIN   ChiYu = 1
	ChiYu_CY_ZHUAN_ZHU ChiYu = 2
	ChiYu_CY_JI_SU     ChiYu = 3
)

// Enum value maps for ChiYu.
var (
	ChiYu_name = map[int32]string{
		0: "CY_QIANG_DU",
		1: "CY_HUI_XIN",
		2: "CY_ZHUAN_ZHU",
		3: "CY_JI_SU",
	}
	ChiYu_value = map[string]int32{
		"CY_QIANG_DU":  0,
		"CY_HUI_XIN":   1,
		"CY_ZHUAN_ZHU": 2,
		"CY_JI_SU":     3,
	}
)

func (x ChiYu) Enum() *ChiYu {
	p := new(ChiYu)
	*p = x
	return p
}

func (x ChiYu) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChiYu) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_attribute_proto_enumTypes[0].Descriptor()
}

func (ChiYu) Type() protoreflect.EnumType {
	return &file_proto_attribute_proto_enumTypes[0]
}

func (x ChiYu) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChiYu.Descriptor instead.
func (ChiYu) EnumDescriptor() ([]byte, []int) {
	return file_proto_attribute_proto_rawDescGZIP(), []int{0}
}

// ZhiYou Buff
// Next field: 3
type ZhiYou int32

const (
	ZhiYou_ZY_ZHUAN_JING ZhiYou = 0
	ZhiYou_ZY_QIANG_DU   ZhiYou = 1
	ZhiYou_ZY_HUI_XIN    ZhiYou = 2
)

// Enum value maps for ZhiYou.
var (
	ZhiYou_name = map[int32]string{
		0: "ZY_ZHUAN_JING",
		1: "ZY_QIANG_DU",
		2: "ZY_HUI_XIN",
	}
	ZhiYou_value = map[string]int32{
		"ZY_ZHUAN_JING": 0,
		"ZY_QIANG_DU":   1,
		"ZY_HUI_XIN":    2,
	}
)

func (x ZhiYou) Enum() *ZhiYou {
	p := new(ZhiYou)
	*p = x
	return p
}

func (x ZhiYou) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ZhiYou) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_attribute_proto_enumTypes[1].Descriptor()
}

func (ZhiYou) Type() protoreflect.EnumType {
	return &file_proto_attribute_proto_enumTypes[1]
}

func (x ZhiYou) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ZhiYou.Descriptor instead.
func (ZhiYou) EnumDescriptor() ([]byte, []int) {
	return file_proto_attribute_proto_rawDescGZIP(), []int{1}
}

// The attribute points of a player.
// Next field: 11
type Attribute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QiangDu        float32  `protobuf:"fixed32,1,opt,name=qiang_du,json=qiangDu,proto3" json:"qiang_du,omitempty"`
	ZhuanJing      float32  `protobuf:"fixed32,2,opt,name=zhuan_jing,json=zhuanJing,proto3" json:"zhuan_jing,omitempty"`
	HuiXin         float32  `protobuf:"fixed32,3,opt,name=hui_xin,json=huiXin,proto3" json:"hui_xin,omitempty"`
	HuiXinShangHai float32  `protobuf:"fixed32,4,opt,name=hui_xin_shang_hai,json=huiXinShangHai,proto3" json:"hui_xin_shang_hai,omitempty"`
	ZhuanZhu       float32  `protobuf:"fixed32,5,opt,name=zhuan_zhu,json=zhuanZhu,proto3" json:"zhuan_zhu,omitempty"`
	JiSu           float32  `protobuf:"fixed32,6,opt,name=ji_su,json=jiSu,proto3" json:"ji_su,omitempty"`
	GongJi         int32    `protobuf:"varint,7,opt,name=gong_ji,json=gongJi,proto3" json:"gong_ji,omitempty"`
	ShuXing        int32    `protobuf:"varint,8,opt,name=shu_xing,json=shuXing,proto3" json:"shu_xing,omitempty"`
	ChiyuBuff      ChiYu    `protobuf:"varint,9,opt,name=chiyu_buff,json=chiyuBuff,proto3,enum=gujian.calculation.ChiYu" json:"chiyu_buff,omitempty"`
	ZhiyouBuff     []ZhiYou `protobuf:"varint,10,rep,packed,name=zhiyou_buff,json=zhiyouBuff,proto3,enum=gujian.calculation.ZhiYou" json:"zhiyou_buff,omitempty"`
}

func (x *Attribute) Reset() {
	*x = Attribute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_attribute_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attribute) ProtoMessage() {}

func (x *Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_proto_attribute_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attribute.ProtoReflect.Descriptor instead.
func (*Attribute) Descriptor() ([]byte, []int) {
	return file_proto_attribute_proto_rawDescGZIP(), []int{0}
}

func (x *Attribute) GetQiangDu() float32 {
	if x != nil {
		return x.QiangDu
	}
	return 0
}

func (x *Attribute) GetZhuanJing() float32 {
	if x != nil {
		return x.ZhuanJing
	}
	return 0
}

func (x *Attribute) GetHuiXin() float32 {
	if x != nil {
		return x.HuiXin
	}
	return 0
}

func (x *Attribute) GetHuiXinShangHai() float32 {
	if x != nil {
		return x.HuiXinShangHai
	}
	return 0
}

func (x *Attribute) GetZhuanZhu() float32 {
	if x != nil {
		return x.ZhuanZhu
	}
	return 0
}

func (x *Attribute) GetJiSu() float32 {
	if x != nil {
		return x.JiSu
	}
	return 0
}

func (x *Attribute) GetGongJi() int32 {
	if x != nil {
		return x.GongJi
	}
	return 0
}

func (x *Attribute) GetShuXing() int32 {
	if x != nil {
		return x.ShuXing
	}
	return 0
}

func (x *Attribute) GetChiyuBuff() ChiYu {
	if x != nil {
		return x.ChiyuBuff
	}
	return ChiYu_CY_QIANG_DU
}

func (x *Attribute) GetZhiyouBuff() []ZhiYou {
	if x != nil {
		return x.ZhiyouBuff
	}
	return nil
}

// The change of dps (in percentage).
// Next field: 11
type AttrEffect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QiangDu        float32 `protobuf:"fixed32,1,opt,name=qiang_du,json=qiangDu,proto3" json:"qiang_du,omitempty"`
	ZhuanJing      float32 `protobuf:"fixed32,2,opt,name=zhuan_jing,json=zhuanJing,proto3" json:"zhuan_jing,omitempty"`
	HuiXin         float32 `protobuf:"fixed32,3,opt,name=hui_xin,json=huiXin,proto3" json:"hui_xin,omitempty"`
	HuiXinShangHai float32 `protobuf:"fixed32,4,opt,name=hui_xin_shang_hai,json=huiXinShangHai,proto3" json:"hui_xin_shang_hai,omitempty"`
	ZhuanZhu       float32 `protobuf:"fixed32,5,opt,name=zhuan_zhu,json=zhuanZhu,proto3" json:"zhuan_zhu,omitempty"`
	JiSu           float32 `protobuf:"fixed32,6,opt,name=ji_su,json=jiSu,proto3" json:"ji_su,omitempty"`
	GongJi         float32 `protobuf:"fixed32,7,opt,name=gong_ji,json=gongJi,proto3" json:"gong_ji,omitempty"`
	ShuXing        float32 `protobuf:"fixed32,8,opt,name=shu_xing,json=shuXing,proto3" json:"shu_xing,omitempty"`
	ChiyuBuff      float32 `protobuf:"fixed32,9,opt,name=chiyu_buff,json=chiyuBuff,proto3" json:"chiyu_buff,omitempty"`
	ZhiyouBuff     float32 `protobuf:"fixed32,10,opt,name=zhiyou_buff,json=zhiyouBuff,proto3" json:"zhiyou_buff,omitempty"`
}

func (x *AttrEffect) Reset() {
	*x = AttrEffect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_attribute_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttrEffect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttrEffect) ProtoMessage() {}

func (x *AttrEffect) ProtoReflect() protoreflect.Message {
	mi := &file_proto_attribute_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttrEffect.ProtoReflect.Descriptor instead.
func (*AttrEffect) Descriptor() ([]byte, []int) {
	return file_proto_attribute_proto_rawDescGZIP(), []int{1}
}

func (x *AttrEffect) GetQiangDu() float32 {
	if x != nil {
		return x.QiangDu
	}
	return 0
}

func (x *AttrEffect) GetZhuanJing() float32 {
	if x != nil {
		return x.ZhuanJing
	}
	return 0
}

func (x *AttrEffect) GetHuiXin() float32 {
	if x != nil {
		return x.HuiXin
	}
	return 0
}

func (x *AttrEffect) GetHuiXinShangHai() float32 {
	if x != nil {
		return x.HuiXinShangHai
	}
	return 0
}

func (x *AttrEffect) GetZhuanZhu() float32 {
	if x != nil {
		return x.ZhuanZhu
	}
	return 0
}

func (x *AttrEffect) GetJiSu() float32 {
	if x != nil {
		return x.JiSu
	}
	return 0
}

func (x *AttrEffect) GetGongJi() float32 {
	if x != nil {
		return x.GongJi
	}
	return 0
}

func (x *AttrEffect) GetShuXing() float32 {
	if x != nil {
		return x.ShuXing
	}
	return 0
}

func (x *AttrEffect) GetChiyuBuff() float32 {
	if x != nil {
		return x.ChiyuBuff
	}
	return 0
}

func (x *AttrEffect) GetZhiyouBuff() float32 {
	if x != nil {
		return x.ZhiyouBuff
	}
	return 0
}

// The conversion between attribute points and attribute percentages.
// Next field: 6
type AttrConversion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QiangDu   float32   `protobuf:"fixed32,1,opt,name=qiang_du,json=qiangDu,proto3" json:"qiang_du,omitempty"`
	ZhuanJing []float32 `protobuf:"fixed32,2,rep,packed,name=zhuan_jing,json=zhuanJing,proto3" json:"zhuan_jing,omitempty"`
	HuiXin    float32   `protobuf:"fixed32,3,opt,name=hui_xin,json=huiXin,proto3" json:"hui_xin,omitempty"`
	ZhuanZhu  float32   `protobuf:"fixed32,4,opt,name=zhuan_zhu,json=zhuanZhu,proto3" json:"zhuan_zhu,omitempty"`
	JiSu      float32   `protobuf:"fixed32,5,opt,name=ji_su,json=jiSu,proto3" json:"ji_su,omitempty"`
}

func (x *AttrConversion) Reset() {
	*x = AttrConversion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_attribute_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttrConversion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttrConversion) ProtoMessage() {}

func (x *AttrConversion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_attribute_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttrConversion.ProtoReflect.Descriptor instead.
func (*AttrConversion) Descriptor() ([]byte, []int) {
	return file_proto_attribute_proto_rawDescGZIP(), []int{2}
}

func (x *AttrConversion) GetQiangDu() float32 {
	if x != nil {
		return x.QiangDu
	}
	return 0
}

func (x *AttrConversion) GetZhuanJing() []float32 {
	if x != nil {
		return x.ZhuanJing
	}
	return nil
}

func (x *AttrConversion) GetHuiXin() float32 {
	if x != nil {
		return x.HuiXin
	}
	return 0
}

func (x *AttrConversion) GetZhuanZhu() float32 {
	if x != nil {
		return x.ZhuanZhu
	}
	return 0
}

func (x *AttrConversion) GetJiSu() float32 {
	if x != nil {
		return x.JiSu
	}
	return 0
}

var File_proto_attribute_proto protoreflect.FileDescriptor

var file_proto_attribute_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x67, 0x75, 0x6a, 0x69, 0x61, 0x6e, 0x2e,
	0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xe6, 0x02, 0x0a, 0x09,
	0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x71, 0x69, 0x61,
	0x6e, 0x67, 0x5f, 0x64, 0x75, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x71, 0x69, 0x61,
	0x6e, 0x67, 0x44, 0x75, 0x12, 0x1d, 0x0a, 0x0a, 0x7a, 0x68, 0x75, 0x61, 0x6e, 0x5f, 0x6a, 0x69,
	0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x7a, 0x68, 0x75, 0x61, 0x6e, 0x4a,
	0x69, 0x6e, 0x67, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x75, 0x69, 0x5f, 0x78, 0x69, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x68, 0x75, 0x69, 0x58, 0x69, 0x6e, 0x12, 0x29, 0x0a, 0x11,
	0x68, 0x75, 0x69, 0x5f, 0x78, 0x69, 0x6e, 0x5f, 0x73, 0x68, 0x61, 0x6e, 0x67, 0x5f, 0x68, 0x61,
	0x69, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0e, 0x68, 0x75, 0x69, 0x58, 0x69, 0x6e, 0x53,
	0x68, 0x61, 0x6e, 0x67, 0x48, 0x61, 0x69, 0x12, 0x1b, 0x0a, 0x09, 0x7a, 0x68, 0x75, 0x61, 0x6e,
	0x5f, 0x7a, 0x68, 0x75, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x7a, 0x68, 0x75, 0x61,
	0x6e, 0x5a, 0x68, 0x75, 0x12, 0x13, 0x0a, 0x05, 0x6a, 0x69, 0x5f, 0x73, 0x75, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x04, 0x6a, 0x69, 0x53, 0x75, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x6f, 0x6e,
	0x67, 0x5f, 0x6a, 0x69, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x67, 0x6f, 0x6e, 0x67,
	0x4a, 0x69, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x68, 0x75, 0x5f, 0x78, 0x69, 0x6e, 0x67, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x68, 0x75, 0x58, 0x69, 0x6e, 0x67, 0x12, 0x38, 0x0a,
	0x0a, 0x63, 0x68, 0x69, 0x79, 0x75, 0x5f, 0x62, 0x75, 0x66, 0x66, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x19, 0x2e, 0x67, 0x75, 0x6a, 0x69, 0x61, 0x6e, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x68, 0x69, 0x59, 0x75, 0x52, 0x09, 0x63, 0x68,
	0x69, 0x79, 0x75, 0x42, 0x75, 0x66, 0x66, 0x12, 0x3b, 0x0a, 0x0b, 0x7a, 0x68, 0x69, 0x79, 0x6f,
	0x75, 0x5f, 0x62, 0x75, 0x66, 0x66, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x67,
	0x75, 0x6a, 0x69, 0x61, 0x6e, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x5a, 0x68, 0x69, 0x59, 0x6f, 0x75, 0x52, 0x0a, 0x7a, 0x68, 0x69, 0x79, 0x6f, 0x75,
	0x42, 0x75, 0x66, 0x66, 0x22, 0xb0, 0x02, 0x0a, 0x0a, 0x41, 0x74, 0x74, 0x72, 0x45, 0x66, 0x66,
	0x65, 0x63, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x71, 0x69, 0x61, 0x6e, 0x67, 0x5f, 0x64, 0x75, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x71, 0x69, 0x61, 0x6e, 0x67, 0x44, 0x75, 0x12, 0x1d,
	0x0a, 0x0a, 0x7a, 0x68, 0x75, 0x61, 0x6e, 0x5f, 0x6a, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x09, 0x7a, 0x68, 0x75, 0x61, 0x6e, 0x4a, 0x69, 0x6e, 0x67, 0x12, 0x17, 0x0a,
	0x07, 0x68, 0x75, 0x69, 0x5f, 0x78, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06,
	0x68, 0x75, 0x69, 0x58, 0x69, 0x6e, 0x12, 0x29, 0x0a, 0x11, 0x68, 0x75, 0x69, 0x5f, 0x78, 0x69,
	0x6e, 0x5f, 0x73, 0x68, 0x61, 0x6e, 0x67, 0x5f, 0x68, 0x61, 0x69, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x0e, 0x68, 0x75, 0x69, 0x58, 0x69, 0x6e, 0x53, 0x68, 0x61, 0x6e, 0x67, 0x48, 0x61,
	0x69, 0x12, 0x1b, 0x0a, 0x09, 0x7a, 0x68, 0x75, 0x61, 0x6e, 0x5f, 0x7a, 0x68, 0x75, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x7a, 0x68, 0x75, 0x61, 0x6e, 0x5a, 0x68, 0x75, 0x12, 0x13,
	0x0a, 0x05, 0x6a, 0x69, 0x5f, 0x73, 0x75, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x6a,
	0x69, 0x53, 0x75, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x6f, 0x6e, 0x67, 0x5f, 0x6a, 0x69, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x67, 0x6f, 0x6e, 0x67, 0x4a, 0x69, 0x12, 0x19, 0x0a, 0x08,
	0x73, 0x68, 0x75, 0x5f, 0x78, 0x69, 0x6e, 0x67, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07,
	0x73, 0x68, 0x75, 0x58, 0x69, 0x6e, 0x67, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x69, 0x79, 0x75,
	0x5f, 0x62, 0x75, 0x66, 0x66, 0x18, 0x09, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x63, 0x68, 0x69,
	0x79, 0x75, 0x42, 0x75, 0x66, 0x66, 0x12, 0x1f, 0x0a, 0x0b, 0x7a, 0x68, 0x69, 0x79, 0x6f, 0x75,
	0x5f, 0x62, 0x75, 0x66, 0x66, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x7a, 0x68, 0x69,
	0x79, 0x6f, 0x75, 0x42, 0x75, 0x66, 0x66, 0x22, 0x95, 0x01, 0x0a, 0x0e, 0x41, 0x74, 0x74, 0x72,
	0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x71, 0x69,
	0x61, 0x6e, 0x67, 0x5f, 0x64, 0x75, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x71, 0x69,
	0x61, 0x6e, 0x67, 0x44, 0x75, 0x12, 0x1d, 0x0a, 0x0a, 0x7a, 0x68, 0x75, 0x61, 0x6e, 0x5f, 0x6a,
	0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x03, 0x28, 0x02, 0x52, 0x09, 0x7a, 0x68, 0x75, 0x61, 0x6e,
	0x4a, 0x69, 0x6e, 0x67, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x75, 0x69, 0x5f, 0x78, 0x69, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x68, 0x75, 0x69, 0x58, 0x69, 0x6e, 0x12, 0x1b, 0x0a,
	0x09, 0x7a, 0x68, 0x75, 0x61, 0x6e, 0x5f, 0x7a, 0x68, 0x75, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x08, 0x7a, 0x68, 0x75, 0x61, 0x6e, 0x5a, 0x68, 0x75, 0x12, 0x13, 0x0a, 0x05, 0x6a, 0x69,
	0x5f, 0x73, 0x75, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x6a, 0x69, 0x53, 0x75, 0x2a,
	0x48, 0x0a, 0x05, 0x43, 0x68, 0x69, 0x59, 0x75, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x59, 0x5f, 0x51,
	0x49, 0x41, 0x4e, 0x47, 0x5f, 0x44, 0x55, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x59, 0x5f,
	0x48, 0x55, 0x49, 0x5f, 0x58, 0x49, 0x4e, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x43, 0x59, 0x5f,
	0x5a, 0x48, 0x55, 0x41, 0x4e, 0x5f, 0x5a, 0x48, 0x55, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x43,
	0x59, 0x5f, 0x4a, 0x49, 0x5f, 0x53, 0x55, 0x10, 0x03, 0x2a, 0x3c, 0x0a, 0x06, 0x5a, 0x68, 0x69,
	0x59, 0x6f, 0x75, 0x12, 0x11, 0x0a, 0x0d, 0x5a, 0x59, 0x5f, 0x5a, 0x48, 0x55, 0x41, 0x4e, 0x5f,
	0x4a, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x5a, 0x59, 0x5f, 0x51, 0x49, 0x41,
	0x4e, 0x47, 0x5f, 0x44, 0x55, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x5a, 0x59, 0x5f, 0x48, 0x55,
	0x49, 0x5f, 0x58, 0x49, 0x4e, 0x10, 0x02, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x3b, 0x63, 0x61, 0x6c,
	0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_attribute_proto_rawDescOnce sync.Once
	file_proto_attribute_proto_rawDescData = file_proto_attribute_proto_rawDesc
)

func file_proto_attribute_proto_rawDescGZIP() []byte {
	file_proto_attribute_proto_rawDescOnce.Do(func() {
		file_proto_attribute_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_attribute_proto_rawDescData)
	})
	return file_proto_attribute_proto_rawDescData
}

var file_proto_attribute_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_attribute_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_attribute_proto_goTypes = []interface{}{
	(ChiYu)(0),             // 0: gujian.calculation.ChiYu
	(ZhiYou)(0),            // 1: gujian.calculation.ZhiYou
	(*Attribute)(nil),      // 2: gujian.calculation.Attribute
	(*AttrEffect)(nil),     // 3: gujian.calculation.AttrEffect
	(*AttrConversion)(nil), // 4: gujian.calculation.AttrConversion
}
var file_proto_attribute_proto_depIdxs = []int32{
	0, // 0: gujian.calculation.Attribute.chiyu_buff:type_name -> gujian.calculation.ChiYu
	1, // 1: gujian.calculation.Attribute.zhiyou_buff:type_name -> gujian.calculation.ZhiYou
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_attribute_proto_init() }
func file_proto_attribute_proto_init() {
	if File_proto_attribute_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_attribute_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Attribute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_attribute_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttrEffect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_attribute_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttrConversion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_attribute_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_attribute_proto_goTypes,
		DependencyIndexes: file_proto_attribute_proto_depIdxs,
		EnumInfos:         file_proto_attribute_proto_enumTypes,
		MessageInfos:      file_proto_attribute_proto_msgTypes,
	}.Build()
	File_proto_attribute_proto = out.File
	file_proto_attribute_proto_rawDesc = nil
	file_proto_attribute_proto_goTypes = nil
	file_proto_attribute_proto_depIdxs = nil
}
