// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package calculation

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// CalculateClient is the client API for Calculate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CalculateClient interface {
	// AttributeCompare calculates demage increment/decrement according to the original & new attributes.
	AttributeCompare(ctx context.Context, in *AttributeCompareRequest, opts ...grpc.CallOption) (*AttributeCompareResponse, error)
}

type calculateClient struct {
	cc grpc.ClientConnInterface
}

func NewCalculateClient(cc grpc.ClientConnInterface) CalculateClient {
	return &calculateClient{cc}
}

func (c *calculateClient) AttributeCompare(ctx context.Context, in *AttributeCompareRequest, opts ...grpc.CallOption) (*AttributeCompareResponse, error) {
	out := new(AttributeCompareResponse)
	err := c.cc.Invoke(ctx, "/gujian.calculation.Calculate/AttributeCompare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalculateServer is the server API for Calculate service.
// All implementations must embed UnimplementedCalculateServer
// for forward compatibility
type CalculateServer interface {
	// AttributeCompare calculates demage increment/decrement according to the original & new attributes.
	AttributeCompare(context.Context, *AttributeCompareRequest) (*AttributeCompareResponse, error)
	mustEmbedUnimplementedCalculateServer()
}

// UnimplementedCalculateServer must be embedded to have forward compatible implementations.
type UnimplementedCalculateServer struct {
}

func (UnimplementedCalculateServer) AttributeCompare(context.Context, *AttributeCompareRequest) (*AttributeCompareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AttributeCompare not implemented")
}
func (UnimplementedCalculateServer) mustEmbedUnimplementedCalculateServer() {}

// UnsafeCalculateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalculateServer will
// result in compilation errors.
type UnsafeCalculateServer interface {
	mustEmbedUnimplementedCalculateServer()
}

func RegisterCalculateServer(s grpc.ServiceRegistrar, srv CalculateServer) {
	s.RegisterService(&_Calculate_serviceDesc, srv)
}

func _Calculate_AttributeCompare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttributeCompareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculateServer).AttributeCompare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gujian.calculation.Calculate/AttributeCompare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculateServer).AttributeCompare(ctx, req.(*AttributeCompareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Calculate_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gujian.calculation.Calculate",
	HandlerType: (*CalculateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AttributeCompare",
			Handler:    _Calculate_AttributeCompare_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/server.proto",
}
